/** @type {import('tailwindcss').Config} */
module.exports = { 
  content: ['./*.html', './**/*.html'],

        darkMode: "class",
        theme: {
          extend: {
            colors: {
              "on-background": "#131d24",
              "surface-container-high": "#dfe9f4",
              "surface-container-low": "#ebf5ff",
              "sea-foam": "#C1CDDA",
              "surface-bright": "#f6f9ff",
              "whatsapp-green": "#008060",
              "on-primary-fixed-variant": "#274871",
              "primary-fixed": "#d4e3ff",
              "pure-white": "#FFFFFF",
              "surface-container": "#e5effa",
              "surface-tint": "#40608a",
              "tertiary-container": "#002a51",
              "outline-variant": "#c3c6cf",
              "ocean-deep": "#15364B",
              "secondary-container": "#8eb3ff",
              "on-surface": "#131d24",
              "surface-variant": "#dae4ef",
              "on-tertiary-fixed-variant": "#004883",
              "on-tertiary-fixed": "#001c39",
              "secondary-fixed": "#d8e2ff",
              background: "#f6f9ff",
              "ocean-mist": "#4B6B7E",
              "inverse-surface": "#28313a",
              "on-secondary-fixed-variant": "#17458a",
              "secondary-fixed-dim": "#adc6ff",
              "card-start-navy": "#0A2247",
              "primary-container": "#002a52",
              ink: "#071532",
              primary: "#00152f",
              "on-surface-variant": "#43474e",
              "inverse-on-surface": "#e8f2fd",
              "error-container": "#ffdad6",
              "inverse-primary": "#a9c8f9",
              "on-error-container": "#93000a",
              "on-tertiary-container": "#4c93e6",
              "on-tertiary": "#ffffff",
              "ocean-teal": "#27475C",
              secondary: "#355da3",
              "on-primary": "#ffffff",
              "card-border": "#0F3976",
              "on-secondary-fixed": "#001a41",
              tertiary: "#00152e",
              "on-primary-fixed": "#001c3a",
              "surface-dim": "#d1dbe6",
              "surface-container-lowest": "#ffffff",
              "tertiary-fixed-dim": "#a4c9ff",
              error: "#ba1a1a",
              "primary-fixed-dim": "#a9c8f9",
              "on-secondary": "#ffffff",
              "on-error": "#ffffff",
              "on-primary-container": "#7392c0",
              "on-secondary-container": "#154388",
              surface: "#f6f9ff",
              "tertiary-fixed": "#d4e3ff",
              outline: "#73777f",
              "surface-container-highest": "#dae4ef",
            },
            borderRadius: {
              DEFAULT: "0.25rem",
              lg: "0.5rem",
              xl: "0.75rem",
              full: "9999px",
            },
            spacing: {
              "space-lg": "1.25rem",
              "space-3xl": "3rem",
              "space-2xl": "2rem",
              "space-xs": "0.25rem",
              "gutter-mobile": "1rem",
              "space-md": "1rem",
              "margin-mobile": "1.25rem",
              "space-xl": "1.5rem",
              gutter: "2rem",
              margin: "2rem",
              "space-sm": "0.5rem",
            },
            fontFamily: {
              "eyebrow-mobile": ["Inter", "sans-serif"],
              "display-hero-mobile": ["Inter", "sans-serif"],
              "headline-lg": ["Inter", "sans-serif"],
              "display-hero": ["Inter", "sans-serif"],
              "body-hero": ["Inter", "sans-serif"],
              "body-lg": ["Inter", "sans-serif"],
              "spec-value": ["Inter", "sans-serif"],
              "headline-md": ["Inter", "sans-serif"],
              eyebrow: ["Inter", "sans-serif"],
              "button-text": ["Inter", "sans-serif"],
              "body-md": ["Inter", "sans-serif"],
              "headline-lg-mobile": ["Inter", "sans-serif"],
              "spec-label": ["Inter", "sans-serif"],
              "headline-md-mobile": ["Inter", "sans-serif"],
            },
            fontSize: {
              "eyebrow-mobile": [
                "12px",
                {
                  lineHeight: "18px",
                  letterSpacing: "0.12em",
                  fontWeight: "600",
                },
              ],
              "display-hero-mobile": [
                "28px",
                {
                  lineHeight: "36px",
                  letterSpacing: "-0.01em",
                  fontWeight: "700",
                },
              ],
              "headline-lg": [
                "28px",
                {
                  lineHeight: "36px",
                  letterSpacing: "-0.01em",
                  fontWeight: "700",
                },
              ],
              "display-hero": [
                "40px",
                {
                  lineHeight: "48px",
                  letterSpacing: "-0.02em",
                  fontWeight: "700",
                },
              ],
              "body-hero": [
                "15px",
                { lineHeight: "24px", letterSpacing: "0em", fontWeight: "400" },
              ],
              "body-lg": [
                "14px",
                { lineHeight: "22px", letterSpacing: "0em", fontWeight: "400" },
              ],
              "spec-value": [
                "14px",
                { lineHeight: "20px", letterSpacing: "0em", fontWeight: "400" },
              ],
              "headline-md": [
                "18px",
                {
                  lineHeight: "26px",
                  letterSpacing: "0.02em",
                  fontWeight: "700",
                },
              ],
              eyebrow: [
                "14px",
                {
                  lineHeight: "20px",
                  letterSpacing: "0.12em",
                  fontWeight: "600",
                },
              ],
              "button-text": [
                "16px",
                {
                  lineHeight: "24px",
                  letterSpacing: "0.01em",
                  fontWeight: "600",
                },
              ],
              "body-md": [
                "14px",
                { lineHeight: "22px", letterSpacing: "0em", fontWeight: "400" },
              ],
              "headline-lg-mobile": [
                "22px",
                {
                  lineHeight: "30px",
                  letterSpacing: "-0.01em",
                  fontWeight: "700",
                },
              ],
              "spec-label": [
                "14px",
                {
                  lineHeight: "20px",
                  letterSpacing: "0.02em",
                  fontWeight: "600",
                },
              ],
              "headline-md-mobile": [
                "18px",
                {
                  lineHeight: "26px",
                  letterSpacing: "0.02em",
                  fontWeight: "700",
                },
              ],
            },
          },
        },
      };