import json

with open(r'C:\project\ventimaxsolutions\texts_to_translate.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

translations = {
  'Diameter Terbesar di Dunia (> 1.000 mm)': 'Largest Diameter in the World (> 1,000 mm)',
  'Pelepasan Udara Hangat Secara Berkesinambungan': 'Continuous Warm Air Exhaust',
  'Fitur & Keunggulan Utama': 'Key Features & Benefits',
  'Dirancang untuk beban angin siklonik ekstrem & sertifikasi ketahanan struktural internasional.': 'Designed for extreme cyclonic wind loads & certified for international structural resistance.',
  'Dapatkan estimasi kebutuhan termal dan penawaran terbaik untuk insulasi atap cuma-cuma dari tim ahli\n                kami.': 'Get a thermal requirement estimate and the best quote for roof insulation for free from our expert team.',
  'Balanced gradient overlay with reduced opacity matching Beranda': 'Balanced gradient overlay with reduced opacity matching Beranda',
  'Dapatkan estimasi kebutuhan titik ventilasi dan penawaran terbaik untuk atap Anda cuma-cuma dari tim ahli kami.': 'Get a ventilation point requirement estimate and the best quote for your roof for free from our expert team.',
  'Standar Rekayasa Arsitektur': 'Architectural Engineering Standards',
  'Material polikarbonat UV-stabilized tidak teroksidasi oleh uap garam laut ataupun panas terik tropis.': 'UV-stabilized polycarbonate material does not oxidize from sea salt vapor or intense tropical heat.',
  'Mereduksi kelembapan dan pengembunan plafon': 'Reduces ceiling humidity and condensation',
  'Mengurangi beban operasional AC dan pencahayaan lampu buatan pada area lantai atas.': 'Reduces AC operational load and artificial lighting on upper floor areas.',
  'Uji beban angin siklonik ekstrem dan stabilitas termal tanpa memerlukan asupan daya listrik apapun.': 'Extreme cyclonic wind load test and thermal stability without requiring any electrical power supply.',
  'Dibangun dengan Marine Grade Aluminium pilihan: anti-karat, anti-bocor, serta minim perawatan bahkan saat terpapar curah hujan tropis monsun dan terpaan angin badai.': 'Built with selected Marine Grade Aluminium: anti-rust, anti-leak, and minimal maintenance even when exposed to tropical monsoon rainfall and hurricane winds.',
  'Diameter Terbesar di Dunia': 'Largest Diameter in the World',
  'Kemurnian Aluminium Foil': 'Aluminium Foil Purity',
  'Layanan Pemasangan & Tim Berpengalaman': 'Installation Services & Experienced Team',
  'Keunggulan 5: Reliable Warranty': 'Advantage 5: Reliable Warranty',
  'Ventilator\n                    Atap VentiMax': 'VentiMax Roof Ventilator',
  'Dimensi Luar (cm)': 'Outer Dimensions (cm)',
  'Atap Dek Logam': 'Metal Deck Roof',
  'Aluminium / Logam Ringan Presisi': 'Precision Aluminium / Light Metal',
  'Optimalkan Hunian & Bangunan Anda dengan VentiCool': 'Optimize Your Home & Building with VentiCool',
  'Standar Rekayasa Ventilasi Bergaransi Resmi Venti Max Solutions': 'Ventilation Engineering Standards with Official Venti Max Solutions Warranty',
  'Instalasi Atap Nyata': 'Real Roof Installation',
  'Ventilasi Alami & Pencahayaan Skylight Bawah Atap': 'Natural Ventilation & Under-Roof Skylight Daylighting',
  'Sirkulasi Udara Attic / Plafon + Pencahayaan Alami (Daylighting Skylight)': 'Attic / Ceiling Air Circulation + Natural Daylighting (Skylight)',
  'Diameter Tenggorokan (Throat)': 'Throat Diameter',
  'Diagram Struktur Lapisan Atap': 'Roof Layer Structure Diagram',
  'Daya regang tinggi yang\n                      mempermudah proses penarikan dan pemasangan pada atap bentang lebar.': 'High tensile strength that simplifies the pulling and installation process on wide-span roofs.',
  'Penerangan nol listrik di siang hari sekaligus menjaga suhu interior ruang tetap sejuk.': 'Zero-electricity lighting during the day while keeping interior room temperatures cool.',
  'Keunggulan 5': 'Advantage 5',
  'Optimalkan Hunian & Bangunan Anda dengan Supavent Turbo Beam': 'Optimize Your Home & Building with Supavent Turbo Beam',
  'Tersedia dalam berbagai format ketebalan dan densitas gulungan roll untuk kebutuhan residensial,\n                pergudangan modern, hingga fasilitas manufaktur berat.': 'Available in various roll thickness and density formats for residential needs, modern warehousing, to heavy manufacturing facilities.',
  'Isolasi single/double layer dengan proteksi termal fleksibel untuk hunian dan ruko komersial.': 'Single/double layer insulation with flexible thermal protection for homes and commercial shophouses.',
  'Pemasangan presisi oleh tim teknisi berseragam resmi nasional di atap bentang lebar komersial &\n                    industri.': 'Precision installation by a national official uniformed technician team on commercial & industrial wide-span roofs.',
  'Sangat fleksibel diinstalasi pada atap genteng sirap, keramik, beton, spandek, galvalum, maupun genteng metal hunian residensial maupun pergudangan logistik berkapasitas tinggi.': 'Highly flexible for installation on shingle, ceramic, concrete, spandek, galvalum, or metal tile roofs of residential homes and high-capacity logistics warehouses.',
  'Jaminan perlindungan menyeluruh untuk durabilitas struktur turbin dan keandalan mekanis bearing tanpa perlu pelumasan rutin.': 'Comprehensive protection guarantee for turbine structure durability and bearing mechanical reliability without the need for routine lubrication.',
  'Material Marine Grade Aluminium Tahan Korosi': 'Corrosion-Resistant Marine Grade Aluminium Material',
  'Dukungan Penuh Servis & Suku Cadang': 'Full Service & Spare Parts Support',
  'Layanan Pengadaan & Pemasangan Nasional': 'National Procurement & Installation Services',
  'Standar Mutu Industri': 'Industrial Quality Standards',
  'Udara panas dan lembap secara alami bergerak ke atas plafon ruangan. Melalui rancang kisi aerodinamis\n                Ventigrille, udara pengap diteruskan menuju rongga atap untuk dikeluarkan tanpa hambatan melalui\n                ventilator atap VentiMax.': 'Hot and humid air naturally moves up to the room ceiling. Through Ventigrille\'s aerodynamic grille design, stuffy air is passed into the roof cavity to be expelled unhindered through the VentiMax roof ventilator.',
  'Lapisan VentiCool bekerja memantulkan radiasi termal dari sinar matahari langsung sebelum menembus\n                rangka dan plafon bangunan, mereduksi suhu ruang hingga 5°C - 10°C secara alami tanpa beban operasional\n                listrik.': 'The VentiCool layer works by reflecting thermal radiation from direct sunlight before penetrating the building\'s frame and ceiling, naturally reducing room temperatures by 5°C - 10°C without electrical operational loads.',
  'Kompatibilitas Struktur Atap': 'Roof Structure Compatibility',
  'STUDI FISIK PRODUK': 'PRODUCT PHYSICAL STUDY',
  'Keunggulan 4': 'Advantage 4',
  'Keunggulan 1': 'Advantage 1',
  'Aluminium Tahan Korosi': 'Corrosion-Resistant Aluminium',
  'Solusi komprehensif mulai dari turbin industri Hurricane hingga kisi udara arsitektural VentiGrille.': 'Comprehensive solutions ranging from Hurricane industrial turbines to VentiGrille architectural air grilles.',
  'Sirkulasi Ruang Plafon Dingin': 'Cool Ceiling Space Circulation',
  'Harmoni Sirkulasi Udara & Masuknya Cahaya Langit': 'Harmony of Air Circulation & Skylight Entry',
  'Roll aluminium insulasi tahan panas dengan kerapatan tinggi untuk atap baja ringan dan genteng.': 'High-density heat-resistant aluminium insulation roll for light steel and tile roofs.',
  'Diformulasikan dengan aditif penghambat api bersertifikasi untuk perlindungan maksimal aset\n                    bangunan.': 'Formulated with certified fire-retardant additives for maximum protection of building assets.',
  'Integrasi langsung pada kemiringan atap kompleks manufaktur, menjamin ekstraksi udara panas dan uap pekat secara terus menerus.': 'Direct integration onto the roof pitch of manufacturing complexes, ensuring continuous extraction of hot air and dense steam.',
  'Bekerja 100% bertenaga angin dan konveksi termal alami tanpa sambungan listrik. Penghematan energi nyata seumur hidup bangunan Anda.': 'Works 100% powered by wind and natural thermal convection without electrical connections. Real energy savings for the lifetime of your building.',
  'Sangat cocok untuk atap dek logam, polikarbonat, maupun genteng pada hunian, kafe, ruko, workshop, dan bangunan komersial modern.': 'Highly suitable for metal deck, polycarbonate, or tile roofs on homes, cafes, shophouses, workshops, and modern commercial buildings.',
  'Ekstraksi Hawa Panas & Kelembapan 24/7': '24/7 Hot Air & Moisture Extraction',
  'Fungsi Ganda': 'Dual Function',
  'Kepala Akrilik Transparan Berkualitas Tinggi': 'High Quality Transparent Acrylic Head',
  'Fungsi Kedua': 'Second Function',
  'Dirancang untuk melampaui kisi ventilasi konvensional, Ventigrille menyatukan fungsionalitas termal dengan\n              ketelitian visual arsitektural.': 'Designed to surpass conventional ventilation grilles, Ventigrille unites thermal functionality with architectural visual precision.',
  'Detail Dimensi & Aplikasi': 'Dimension & Application Details',
  'Menolak gelombang radiasi\n                      ultraviolet dan inframerah matahari hingga >97%.': 'Rejects up to >97% of solar ultraviolet and infrared radiation waves.',
  'Dek Logam Perak, Minimalis Terang, Putih Gading': 'Silver Metal Deck, Bright Minimalist, Ivory White',
  'Gaya Rustik, Mediterania, Atap Cokelat & Perunggu': 'Rustic Style, Mediterranean, Brown & Bronze Roofs',
  'Pilihan kisi-kisi ventilasi bergaris tegas dalam dimensi bujur sangkar dan persegi panjang untuk memenuhi\n              fleksibilitas denah plafon maupun dinding.': 'A selection of bold-lined ventilation grilles in square and rectangular dimensions to meet the flexibility of ceiling and wall layouts.',
  'Turbin Ventilator Atap Alami (Wind-Driven)': 'Natural Roof Ventilator Turbine (Wind-Driven)',
  'Keunggulan 3': 'Advantage 3',
  'Supavent Turbo Beam memadukan ventilator turbin bertenaga angin alami dengan kubah akrilik bening berkualitas tinggi yang berfungsi ganda sebagai skylight. Menerangi loteng dan ruang bawah atap dengan cahaya matahari gratis sekaligus menghisap hawa panas secara berkelanjutan tanpa listrik.': 'Supavent Turbo Beam combines a natural wind-powered turbine ventilator with a high-quality clear acrylic dome that doubles as a skylight. Illuminates attics and under-roof spaces with free sunlight while continuously extracting hot air without electricity.',
  'Anti-Karat & Mudah Dibersihkan': 'Anti-Rust & Easy to Clean',
  'KISI\n                  VENTILASI ARSITEKTURAL PLAFON & DINDING': 'ARCHITECTURAL CEILING & WALL VENTILATION GRILLE',
  '3. KEUNGGULAN TEKNOLOGI': '3. TECHNOLOGICAL ADVANTAGES',
  'SupaVent Standar': 'Standard SupaVent',
  'Presisi Terhadap Berbagai Profil Atap': 'Precision Across Various Roof Profiles',
  'Genteng Beton/Keramik Hitam, Charcoal, Slate': 'Black, Charcoal, Slate Concrete/Ceramic Tiles',
  'Aluminium Foil Murni + Foam Core Insulasi + Perekat Anti-Delaminasi Presisi Tinggi.': 'Pure Aluminium Foil + Foam Core Insulation + High Precision Anti-Delamination Adhesive.',
  'Dengan ukuran diameter lebih dari satu meter, turbin dirancang khusus untuk membuang volume panas ekstrem pada manufaktur berat, perakitan, dan fasilitas logistik masif.': 'With a diameter of more than one meter, the turbine is specially designed to exhaust extreme heat volumes in heavy manufacturing, assembly, and massive logistics facilities.',
  'Finishing Abu-Abu Serbaguna': 'Versatile Grey Finish',
  'Reflektivitas Panas\n                    Radiasi': 'Radiant Heat Reflectivity',
  'Pilihan warna putih bersih yang\n                    berpadu mulus (seamless blend) dengan permukaan plafon gypsum.': 'Clean white color option that blends seamlessly with gypsum ceiling surfaces.',
  'Dinding Atas Pintu, Koridor, Drop Ceiling': 'Wall Above Door, Corridor, Drop Ceiling',
  'Sistem ventilasi berkinerja tinggi yang mengatasi kendala termal ruang produksi modern secara mandiri dan berkelanjutan.': 'A high-performance ventilation system that overcomes thermal constraints of modern production spaces independently and sustainably.',
  'Dapatkan simulasi teknis kebutuhan sirkulasi dan estimasi pencahayaan atap cuma-cuma dari tim ahli kami.': 'Get a technical simulation of circulation needs and roof daylighting estimates for free from our expert team.',
  'Finishing Matte Klasik & Presisi Laser Mark': 'Classic Matte Finish & Laser Mark Precision',
  'Performa tahan panas ekstrem yang dirancang bagi gudang logistik, pabrik pengolahan, dan hanggar.': 'Extreme heat resistant performance designed for logistics warehouses, processing plants, and hangars.',
  'Berdaya tahan tinggi, tidak berkarat, tidak penyok, dan dirancang khusus menghadapi terik ultraviolet ekstrem.': 'Highly durable, does not rust, does not dent, and specially designed to face extreme ultraviolet heat.',
  'Instalasi Atap Pabrik Nyata': 'Real Factory Roof Installation',
  'Dirancang presisi untuk iklim tropis Indonesia yang lembap, panas, dan membutuhkan durabilitas material jangka panjang.': 'Precision-designed for Indonesia\'s tropical climate which is humid, hot, and requires long-term material durability.',
  'Aerodinamika anti-bising & anti-getar': 'Anti-noise & anti-vibration aerodynamics',
  'Konsep Sirkulasi Berkelanjutan': 'Sustainable Circulation Concept',
  'Tidak menghasilkan dengung resonansi bising benturan air hujan seperti ventilator seng/aluminium biasa.': 'Does not produce noisy resonance hum from rainwater impact like ordinary zinc/aluminium ventilators.',
  'Pemasangan Terpadu Bersama Tim Teknisi Berpengalaman': 'Integrated Installation With an Experienced Technician Team',
  'Dibuat dari akrilik polimer bening UV-stabilized tahan benturan, cuaca ekstrem, dan tidak mudah menguning akibat terik matahari tropis berkepanjangan.': 'Made from clear UV-stabilized polymer acrylic resistant to impact, extreme weather, and does not easily yellow due to prolonged tropical scorching sun.',
  'Inti Penghambat Panas & Api (Fire\n                      Retardant)': 'Heat & Fire Retardant Core',
  '5. KEUNGGULAN UTAMA (BENTO GRID)': '5. KEY ADVANTAGES (BENTO GRID)',
  'Diagram Alir\n                  Termal & Plafon': 'Thermal & Ceiling Flow Diagram',
  'Finishing Hitam': 'Black Finish',
  'Dual precision bearing terlindung kedap debu dan air, berputar mulus tanpa perlu pelumasan ulang.': 'Dual precision bearings protected against dust and water, rotating smoothly without the need for re-lubrication.',
  'Keunggulan material dan rancang bangun presisi yang memberikan performa tanpa tanding sepanjang tahun.': 'Material excellence and precision engineering that deliver unmatched performance year-round.',
  'KEUNGGULAN & SPESIFIKASI': 'ADVANTAGES & SPECIFICATIONS',
  'Format kompak untuk area kamar\n                    mandi, ruang rias, atau zona dinding yang membutuhkan ventilasi ringkas.': 'Compact format for bathroom areas, dressing rooms, or wall zones that require compact ventilation.',
  'Mencegah akumulasi gas polutan dan debu industri': 'Prevents accumulation of pollutant gases and industrial dust',
  'Kubah bening polimer akrilik meneruskan spektrum cahaya matahari ke bawah plafon. Mengeliminasi kebutuhan lampu di area loteng, tangga mezzanine, koridor garasi, dan gudang saat siang hari.': 'The clear acrylic polymer dome transmits the sunlight spectrum beneath the ceiling. Eliminates the need for lights in attics, mezzanine stairs, garage corridors, and warehouses during the day.',
  'Genteng Tanah Liat Terakota, Mediterania & Klasik': 'Terracotta Clay, Mediterranean & Classic Tiles',
  'Kesesuaian Atap': 'Roof Compatibility',
  'Supavent Turbo Beam ideal diaplikasikan pada konfigurasi arsitektur:': 'Supavent Turbo Beam is ideal for architectural configurations:',
  'Kebutuhan Listrik': 'Electricity Needs',
  'Direkayasa dengan presisi aerodinamika tinggi untuk memberikan performa sirkulasi udara masif tanpa konsumsi daya.': 'Engineered with high aerodynamic precision to deliver massive air circulation performance without power consumption.',
  'Memberikan sentuhan skylight modern yang estetik sambil mempertahankan sirkulasi udara sejuk.': 'Provides an aesthetic modern skylight touch while maintaining cool air circulation.',
  'Pilihan Warna Finishing': 'Finishing Color Options',
  'Kapasitas maksimum aliran udara terukur untuk mengatasi suhu tinggi dan kelembapan ekstrem pada atap gudang atau manufaktur skala besar.': 'Maximum measured airflow capacity to overcome high temperatures and extreme humidity in large-scale warehouse or manufacturing roofs.',
  'Setiap varian dilengkapi foto unit detail studio dan instalasi nyata pada profil atap arsitektural. Temukan warna yang menyatu serasi dengan karakter hunian dan bangunan komersial Anda.': 'Each variant is equipped with detailed studio unit photos and real installations on architectural roof profiles. Find colors that blend harmoniously with the character of your home and commercial building.',
  'Ketahanan struktural teruji berstandar pabrikan resmi untuk rasa aman investasi jangka panjang properti.': 'Tested structural resistance with official factory standards for long-term property investment peace of mind.',
  'Keunggulan 4: Wide Compatibility': 'Advantage 4: Wide Compatibility',
  'INSULASI ATAP BERBAHAN ALUMINIUM FOIL': 'ALUMINIUM FOIL BASED ROOF INSULATION',
  'Diformulasikan secara khusus untuk iklim tropis Indonesia dengan performa isolasi teruji dan standar\n              konstruksi industri bangunan masa kini.': 'Specially formulated for Indonesia\'s tropical climate with tested insulation performance and today\'s building industry construction standards.',
  'Transparan tinggi, tahan cuaca ekstrem tropis, tidak mudah buram/kuning': 'Highly transparent, resistant to extreme tropical weather, does not easily blur/yellow',
  'Keunggulan Utama Supavent Turbo Beam': 'Main Advantages of Supavent Turbo Beam',
  '100% Aluminium Murni': '100% Pure Aluminium',
  'Diproduksi menggunakan material aluminium kelas kelautan berdaya tahan tinggi terhadap polusi asam, kelembaban garam pesisir, dan oksidasi cuaca tropis.': 'Manufactured using marine-grade aluminium material with high durability against acid pollution, coastal salt humidity, and tropical weather oxidation.',
  'Keunggulan 2: High Quality Acrylic': 'Advantage 2: High Quality Acrylic',
  'Seri Standar Industri': 'Industrial Standard Series',
  'Inovasi dalam Ventilasi Atap': 'Innovation in Roof Ventilation',
  'Laju Buang Udara (Maksimum)': 'Air Exhaust Rate (Maximum)',
  'Menghalangi perambatan\n                      konduksi termal serta tidak memicu atau memperbesar rambatan kobaran api.': 'Blocks the propagation of thermal conduction and does not trigger or enlarge the spread of flames.',
  'Visual unit Hurricane memperlihatkan bilah melengkung aerodinamis presisi yang mampu berputar responsif bahkan pada kecepatan angin rendah.': 'The Hurricane unit visual shows precision aerodynamic curved blades capable of rotating responsively even at low wind speeds.',
  'Dibuat dari material polikarbonat mutakhir dengan teknologi UV-stabilized standar kualitas Australia. Didesain secara presisi aerodinamis untuk menghadirkan performa maksimal, ventilator ini tahan korosi air laut tropis, tidak mudah berisik saat hujan lebat, dan tidak karatan seperti ventilator logam konvensional.': 'Made from advanced polycarbonate material with Australian quality standard UV-stabilized technology. Designed with aerodynamic precision to deliver maximum performance, this ventilator is resistant to tropical sea water corrosion, not easily noisy during heavy rain, and does not rust like conventional metal ventilators.',
  'Foto Instalasi Atap Nyata': 'Real Roof Installation Photos',
  'Optimalkan Hunian & Bangunan Anda dengan SupaVent': 'Optimize Your Home & Building with SupaVent',
  'Keunggulan 2': 'Advantage 2',
  'Kamar Mandi, Dapur Bersih, Ruang Pakaian': 'Bathroom, Clean Kitchen, Wardrobe Room',
  'Keunggulan Teknologi': 'Technological Advantages',
  'Dilengkapi jaminan keandalan jangka panjang dari PT Venti Max Solutions serta dukungan instalator bersertifikasi di seluruh Indonesia.': 'Equipped with a long-term reliability guarantee from PT Venti Max Solutions and support from certified installers throughout Indonesia.',
  'Rotasi halus pada kecepatan angin rendah': 'Smooth rotation at low wind speeds',
  'Menyatu rata dengan gypsum langit-langit interior\n                    hunian': 'Blends evenly with residential interior ceiling gypsum',
  'Bentuk memanjang yang ideal\n                    ditempatkan di atas pintu, lorong sempit, atau drop-ceiling modern.': 'An elongated shape that is ideal placed above doors, narrow hallways, or modern drop-ceilings.',
  'Formula Tahan Degradasi UV': 'UV Degradation Resistant Formula',
  'Menciptakan kenyamanan termal pekerja secara merata': 'Creates even thermal comfort for workers',
  'Garansi 15 Tahun Masa Pakai Handal': '15-Year Reliable Lifespan Warranty',
  'Menerangi ruang tangga, loteng, dan garasi sekaligus membuang udara pengap bawah genteng.': 'Illuminates stairwells, attics, and garages while exhausting stuffy air beneath the roof tiles.',
  'Kisi ventilasi simetris berbalut\n                    warna hitam matte elegan untuk aksen interior kontemporer.': 'Symmetrical ventilation grille wrapped in elegant matte black for contemporary interior accents.',
  'KEUNGGULAN UTAMA': 'KEY ADVANTAGES',
  'Memadukan sirkulasi udara alami 24/7 tanpa listrik dengan transmisi cahaya alami untuk menerangi area plafon dan loteng secara gratis. Satu investasi perangkat memberikan dua manfaat fungsional arsitektural sekaligus.': 'Combines 24/7 natural air circulation without electricity with natural light transmission to illuminate ceiling and attic areas for free. One device investment provides two architectural functional benefits at once.',
  '100% bertenaga angin dan konveksi termal alami 24/7. Mengurangi beban operasional gedung secara drastis tanpa memerlukan sambungan kabel dan panel kontrol elektrik.': '100% powered by wind and 24/7 natural thermal convection. Drastically reduces building operational loads without the need for cable connections and electrical control panels.',
  'Cokelat Kemerahan': 'Reddish Brown',
  'Setiap unit kisi ventilasi Ventigrille diproduksi dengan toleransi presisi tingkat tinggi. Dilapisi\n                dengan proses pelapisan elektrostatik tahan pudar dan dilengkapi penandaan identitas resmi, menjamin\n                orisinalitas serta daya tahan estetika pada interior jangka panjang.': 'Each Ventigrille ventilation grille unit is manufactured with a high degree of precision tolerance. Coated with a fade-resistant electrostatic coating process and equipped with official identity markings, guaranteeing originality and aesthetic durability in long-term interiors.',
  'Keunggulan 3: Zero Watt': 'Advantage 3: Zero Watt',
  '4. MEKANISME KERJA INOVATIF': '4. INNOVATIVE WORKING MECHANISM',
  'Workshop & Fasilitas Kerja Terang': 'Bright Workshop & Work Facilities',
  'Standar Arsitektur Modern': 'Modern Architectural Standards',
  'Sinergi aerodinamika hembusan angin konvektif dan refraksi radiasi foton alami tanpa memerlukan motor penggerak elektrik.': 'Synergy of convective wind gust aerodynamics and natural photon radiation refraction without requiring an electric drive motor.',
  'Dimensi Resmi:': 'Official Dimensions:',
  'Udara Hangat & Pengap\n                    Interior Naik': 'Warm & Stuffy Interior Air Rises',
  'Didesain di Australia': 'Designed in Australia',
  'Menjaga kelembapan rendah dan visibilitas ruang kerja tetap terang secara alami.': 'Maintains low humidity and naturally bright workspace visibility.',
  'Material pilihan kami memiliki sifat tahan api untuk memberikan perlindungan ekstra dan ketenangan\n                  pikiran. Nikmati solusi menyeluruh yang mencakup pengiriman tepat waktu, pemasangan profesional\n                  berstandar K3, serta garansi resmi hingga 10 tahun.': 'Our selected materials have fire-retardant properties to provide extra protection and peace of mind. Enjoy a comprehensive solution that includes on-time delivery, OHS-standard professional installation, and an official warranty of up to 10 years.',
  'SOP Keamanan Bekerja Ketinggian': 'Working at Heights Safety SOP',
  'MEKANISME KERJA INOVATIF': 'INNOVATIVE WORKING MECHANISM',
  'Keunggulan 1: Large Span': 'Advantage 1: Large Span',
  'FITUR & KEUNGGULAN UTAMA (5 POIN LENGKAP DOKUMEN ASLI)': 'KEY FEATURES & ADVANTAGES (5 COMPLETE POINTS FROM ORIGINAL DOCUMENT)',
  'Hunian Kawasan Pesisir, Atap Nuansa Biru/Netral': 'Coastal Area Homes, Blue/Neutral Nuanced Roofs',
  'Nol watt konsumsi listrik (0 Watt). Memanfaatkan konveksi termal alami dan dorongan angin sepoi-sepoi.': 'Zero watt electricity consumption (0 Watt). Utilizes natural thermal convection and gentle wind push.',
  'Mengeliminasi kantong udara panas di plafon ruang tamu,\n                    kamar, maupun dapur.': 'Eliminates hot air pockets in the ceiling of living rooms, bedrooms, or kitchens.',
  'Hurricane memanfaatkan gaya apung termal (stack effect) di mana udara panas dalam ruangan yang memuai akan bergerak naik dan diekstraksi ke luar oleh bilah turbin yang senantiasa berotasi oleh aliran angin luar.': 'Hurricane utilizes thermal buoyancy (stack effect) where expanding indoor hot air moves up and is extracted out by turbine blades that are constantly rotating by outside wind flows.',
  'Memanfaatkan efek konveksi termal dan daya hisap angin alami. Udara panas yang terjebak di rongga atap ditarik keluar secara terus-menerus sehingga menurunkan suhu interior secara signifikan.': 'Utilizes thermal convection effect and natural wind suction power. Hot air trapped in the roof cavity is drawn out continuously, significantly lowering interior temperatures.',
  'Unit Hurricane Standar Industri': 'Industrial Standard Hurricane Unit',
  'Standar Maritim Internasional': 'International Maritime Standards',
  'Area Pemasangan Rekomendasi': 'Recommended Installation Areas'
}

result_dict = {}
for text in data:
    result_dict[text] = translations.get(text, text)
    
with open(r'C:\project\ventimaxsolutions\translated_dict.json', 'w', encoding='utf-8') as f:
    json.dump(result_dict, f, ensure_ascii=False, indent=2)

print(f'Successfully translated {len(result_dict)} items.')
